---
title: "ggplot2 - Global Map with point data"
output: html_document
---

```{r,warning=FALSE,message=FALSE}
library(rgdal)
library(ggplot2)

```

```{r,echo=FALSE,warning=FALSE,message=FALSE}
#temp<-read.csv("All_LPI_All_Years_Nobuff_1931_moreLPI_end2005.csv")
#temp<-read.csv("All_LPI_Mean_Temp_Slope_nobuff.csv")

luc<-read.csv("Hyde_crop_pasture_annual_change.csv")
LPI<-read.csv("LPI_pops_20160523_edited.csv")

body<-read.csv("bird_and_mammal_traits2.csv")
body2<-read.csv("LPI_traits.csv")

body3<-rbind(body, body2)

body4<-unique(body3[,c(2:5)])

pop<-read.csv("Global_Population_Trends_Rsq_Lambda_07_10_16.csv")

temp<-temp[,c("ID", "Estimate")]

LPI<-LPI[,c("ID","Binomial","Common_name","Country","Region", "System", "Class","Specific_location", "Longitude", "Latitude", "Primary_threat", "Secondary_threat", "Tertiary_threat")]

df<-merge(merge(temp,luc, by="ID", all=TRUE), merge(LPI, pop, by="ID", all=TRUE),by="ID", all=TRUE)

df<-merge(df, body4, by="ID")

locs<-subset(df, !is.na(Estimate)&r_sq >= 0.499999  & !is.na(both_change) & !is.na(Bodymass_g) &
            length_time >=5 & System!="Marine" &Specific_location == 1 &(Class=="Mammalia"|Class=="Aves"))
write.csv(locs, "my_locations2.csv")

```


```{r, eval=FALSE,warning=FALSE,message=FALSE}
locs<-read.csv("my_locations2.csv")

```


```{r,warning=FALSE,message=FALSE}
library(plyr)
#counting duplicates at each location
sp_dups<-data.frame(ddply(locs,.(Longitude,Latitude),nrow))
sp_dups$loc_id<-1:length(sp_dups$Longitude)
sp_dups_df<-merge(sp_dups, locs, by=c("Longitude","Latitude"))
```

```{r,warning=FALSE,message=FALSE}
loc<-data.frame(sp_dups_df$Longitude,sp_dups_df$Latitude,sp_dups_df$V1)
loc<-unique(loc)
colnames(loc)<-c("Longitude", "Latitude", "V1")

coordinates(loc)<-c("Longitude","Latitude")
proj4string(loc) <- CRS("+proj=longlat")
```

```{r,warning=FALSE,message=FALSE,echo=FALSE,eval=FALSE}
wmap <- readOGR(dsn="ne_110m_land.shp", layer="ne_110m_land")
coast<-readOGR(dsn="ne_110m_coastline.shp", layer="ne_110m_coastline")
bbox<-readOGR("ne_10m_wgs84_bounding_box.shp", layer="ne_10m_wgs84_bounding_box") 

```

```{r, eval=FALSE, echo=FALSE,warning=FALSE,message=FALSE}
#wmap <- readOGR(dsn="ne_110m_land.shp", layer="ne_110m_land")
#wmap <- readOGR(dsn="ne_110m_land.shp", layer="ne_110m_coastline")
#countries <- readOGR("ne_50m_admin_0_countries.shp", layer="ne_50m_admin_0_countries")
#bbox<-readOGR("ne_10m_wgs84_bounding_box.shp", layer="ne_10m_wgs84_bounding_box") 
```


```{r,warning=FALSE,message=FALSE, eval=FALSE, echo=FALSE}

wmap_df<-fortify(wmap)
coast_df<-fortify(coast)
loc_df<-data.frame(loc)
bbox_df<-fortify(bbox)

```

```{r}
loc_df<-data.frame(loc)
```

```{r,warning=FALSE,message=FALSE}

theme_opts <- list(theme(panel.grid.minor = element_blank(),
                         panel.grid.major = element_blank(),
                         panel.background = element_blank(),
                         plot.background = element_rect(fill="white"),
                         panel.border = element_blank(),
                         axis.line = element_blank(),
                         axis.text.x = element_blank(),
                         axis.text.y = element_blank(),
                         axis.ticks = element_blank(),
                         axis.title.x = element_blank(),
                         axis.title.y = element_blank(),
                         plot.title = element_text(size=22)))
```

```{r,warning=FALSE,message=FALSE}

library(maps)
library(mapdata)

ggplot(data=loc_df, aes(Longitude, Latitude, group=NULL,fill=NULL,size=V1))+#, fill=hole)) + 
  borders(fill="light grey",colour="light grey")+
  geom_point(color="black",alpha=I(7/10))+
  scale_size(range=c(1,7), guide = "legend",labs(size="No. of Populations"))+
  coord_equal()+
  theme_opts
  

```

```{r,warning=FALSE,message=FALSE}

library(maps)
library(mapdata)

ggplot(data=loc_df, aes(Longitude, Latitude, group=NULL,fill=NULL,size=V1))+#, fill=hole)) + 
  borders(fill="black",colour="black")+
  geom_point(color="orange",alpha=I(7/10))+
  scale_size(range=c(1,7), guide = "legend",labs(size="No. of Populations"))+
  coord_equal()+
  theme_opts
  

```


