---
title: "LUH Land Use Data"
author: "Fiona Spooner"
date: "January 11, 2018"
output: html_document
---

```{r}
library(raster)
```

```{r, eval=FALSE, echo=FALSE}


yr<-as.character(850:2015)
date<-as.Date(yr, format="%Y" )

primf<-brick(paste(getwd(),"/states.nc", sep=""), varname="primf")
primf<-setZ(primf, date, name="year")

primn<-brick(paste(getwd(),"/states.nc", sep=""), varname="primn")
primn<-setZ(primn, date, name="year")

secdf<-brick(paste(getwd(),"/states.nc", sep=""), varname="secdf")
secdf<-setZ(secdf, date, name="year")

secdn<-brick(paste(getwd(),"/states.nc", sep=""), varname="secdn")
secdn<-setZ(secdn, date, name="year")

urban<-brick(paste(getwd(),"/states.nc", sep=""), varname="urban")
urban<-setZ(urban, date, name="year")

pastr<-brick(paste(getwd(),"/states.nc", sep=""), varname="pastr")
pastr<-setZ(pastr, date, name="year")

rnge<-brick(paste(getwd(),"/states.nc", sep=""), varname="range")
rnge<-setZ(rnge, date, name="year")

c3ann<-brick(paste(getwd(),"/states.nc", sep=""), varname="c3ann")
c3ann<-setZ(c3ann, date, name="year")

c4ann<-brick(paste(getwd(),"/states.nc", sep=""), varname="c4ann")
c4ann<-setZ(c4ann, date, name="year")

c3per<-brick(paste(getwd(),"/states.nc", sep=""), varname="c3per")
c3per<-setZ(c3per, date, name="year")

c4per<-brick(paste(getwd(),"/states.nc", sep=""), varname="c4per")
c4per<-setZ(c4per, date, name="year")

c3nfx<-brick(paste(getwd(),"/states.nc", sep=""), varname="c3nfx")
c3nfx<-setZ(c3nfx, date, name="year")

```

```{r, eval=FALSE, echo=FALSE}
primf_cr<-primf[[1091:1166]]
primn_cr<-primn[[1091:1166]]
secdf_cr<-secdf[[1091:1166]]
secdn_cr<-secdn[[1091:1166]]
urban_cr<-urban[[1091:1166]]
pastr_cr<-pastr[[1091:1166]]
rnge_cr<-rnge[[1091:1166]]
c3ann_cr<-c3ann[[1091:1166]]
c4ann_cr<-c4ann[[1091:1166]]
c3per_cr<-c3per[[1091:1166]]
c4per_cr<-c4per[[1091:1166]]
c3nfx_cr<-c3nfx[[1091:1166]]
```

```{r, eval=FALSE, echo=FALSE}
writeRaster(primf_cr, "primf_1940.tif")
writeRaster(primn_cr, "primn_1940.tif")
writeRaster(secdf_cr, "secdf_1940.tif")
writeRaster(secdn_cr, "secdn_1940.tif")
writeRaster(urban_cr, "urban_1940.tif")
writeRaster(pastr_cr, "pastr_1940.tif")
writeRaster(rnge_cr, "rnge_1940.tif")
writeRaster(c3ann_cr, "c3ann_1940.tif")
writeRaster(c4ann_cr, "c4ann_1940.tif")
writeRaster(c3per_cr, "c3per_1940.tif")
writeRaster(c4per_cr, "c4per_1940.tif")
writeRaster(c3nfx_cr, "cnfx_1940.tif")
```

```{r}
primf<-brick("primf_1940.tif")
primn<-brick("primn_1940.tif")
secdf<-brick("secdf_1940.tif")
secdn<-brick("secdn_1940.tif")
urban<-brick("urban_1940.tif")
pastr<-brick("pastr_1940.tif")
rnge<-brick("rnge_1940.tif")
c3ann<-brick("c3ann_1940.tif")
c4ann<-brick("c4ann_1940.tif")
c3per<-brick("c3per_1940.tif")
c4per<-brick("c4per_1940.tif")
c3nfx<-brick("cnfx_1940.tif")
```


```{r}
LPI<-read.csv("LPI_pops_20160523_edited.csv")

LPIsp<-subset(LPI, Specific_location==1 & System !="Marine" & Class != "Actinopterygii"& Class != "Cephalaspidomorphi" )

xy<-data.frame(LPIsp$Longitude, LPIsp$Latitude)

xy<-unique(xy)     #identifying unique locations to extract climate data from 

xy_df<-data.frame(xy)
colnames(xy_df)<-c("lon", "lat")
coordinates(xy_df) <- c("lon", "lat")

head(xy_df)

```


####NEEDS ATTENTION

```{r}

library(doParallel)
library(reshape2)

layers<-list(primf, primn, secdf, secdn, urban, pastr, rnge, c3ann, c4ann, c3per, c4per, c3nfx)

df_out<-data.frame()
for (layer in layers){
  
  name<-gsub("\\d", "",names(layer))
  n<-6  #number of cores to use - not sure how many I can go up to
  cl<-makeCluster(n)
  registerDoParallel(cl)  
  days<-nlayers(layer)    #splitting the data evenly between the cores
  step<-floor(days/n)

    ptime <- system.time({   
      df<- foreach(days, .combine=cbind) %dopar%{
      rasterex <- raster:::extract(layer[[1:days]], xy_df)
        }
      }) 
    ptime 
  stopCluster(cl)

  dates<-1940:2015

  datesr<-rep(dates, each=length(xy_df))

  dfm<-melt(df)

  lon<-xy[,1]
  lat<-xy[,2]

  dfm2<-cbind(name,lon,lat,datesr, dfm)

  df_out<-rbind(df_out, dfm2)
  print(name)
}

```